# Web scraping :

##### Web scraping is an automated method to extract large amounts of data from websites.

In [2]:
import pandas as pd

# Read a .csv from a URL with Pandas

##### Target website: https://www.football-data.co.uk/data.php

In [10]:
# reading 1 csv file from the website
df_premier21 = pd.read_csv('https://www.football-data.co.uk/mmz4281/2122/E0.csv')

In [11]:
df_premier21

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,13/08/2021,20:00,Brentford,Arsenal,2,0,H,1,0,...,1.62,0.50,1.75,2.05,1.81,2.13,2.05,2.17,1.80,2.09
1,E0,14/08/2021,12:30,Man United,Leeds,5,1,H,1,0,...,2.25,-1.00,2.05,1.75,2.17,1.77,2.19,1.93,2.10,1.79
2,E0,14/08/2021,15:00,Burnley,Brighton,1,2,A,1,0,...,1.62,0.25,1.79,2.15,1.81,2.14,1.82,2.19,1.79,2.12
3,E0,14/08/2021,15:00,Chelsea,Crystal Palace,3,0,H,2,0,...,1.94,-1.50,2.05,1.75,2.12,1.81,2.16,1.93,2.06,1.82
4,E0,14/08/2021,15:00,Everton,Southampton,3,1,H,0,1,...,1.67,-0.50,2.05,1.88,2.05,1.88,2.08,1.90,2.03,1.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,22/05/2022,16:00,Crystal Palace,Man United,1,0,H,1,0,...,2.04,0.25,1.68,2.15,1.74,2.23,1.88,2.25,1.74,2.16
376,E0,22/05/2022,16:00,Leicester,Southampton,4,1,H,0,0,...,2.63,-0.75,1.83,2.07,1.88,2.03,1.94,2.26,1.87,2.01
377,E0,22/05/2022,16:00,Liverpool,Wolves,3,1,H,1,1,...,3.28,-2.50,2.02,1.77,2.06,1.83,2.19,1.99,2.07,1.80
378,E0,22/05/2022,16:00,Man City,Aston Villa,3,2,H,0,1,...,3.36,-2.25,2.06,1.84,2.05,1.86,2.09,2.03,2.01,1.87
379,E0,22/05/2022,16:00,Norwich,Tottenham,0,5,A,0,2,...,2.40,1.50,1.95,1.95,1.96,1.94,2.16,1.98,1.99,1.89

In [12]:
df_premire21 = df_premier21.rename(columns={'Date':'date',
                                   'Hometown':'home_town',
                                   'AwayTeam':'away_team',
                                   'FTGH':'home_goals',
                                   'FTGH':'away_goals'})

In [13]:
df_premier21

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,13/08/2021,20:00,Brentford,Arsenal,2,0,H,1,0,...,1.62,0.50,1.75,2.05,1.81,2.13,2.05,2.17,1.80,2.09
1,E0,14/08/2021,12:30,Man United,Leeds,5,1,H,1,0,...,2.25,-1.00,2.05,1.75,2.17,1.77,2.19,1.93,2.10,1.79
2,E0,14/08/2021,15:00,Burnley,Brighton,1,2,A,1,0,...,1.62,0.25,1.79,2.15,1.81,2.14,1.82,2.19,1.79,2.12
3,E0,14/08/2021,15:00,Chelsea,Crystal Palace,3,0,H,2,0,...,1.94,-1.50,2.05,1.75,2.12,1.81,2.16,1.93,2.06,1.82
4,E0,14/08/2021,15:00,Everton,Southampton,3,1,H,0,1,...,1.67,-0.50,2.05,1.88,2.05,1.88,2.08,1.90,2.03,1.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,22/05/2022,16:00,Crystal Palace,Man United,1,0,H,1,0,...,2.04,0.25,1.68,2.15,1.74,2.23,1.88,2.25,1.74,2.16
376,E0,22/05/2022,16:00,Leicester,Southampton,4,1,H,0,0,...,2.63,-0.75,1.83,2.07,1.88,2.03,1.94,2.26,1.87,2.01
377,E0,22/05/2022,16:00,Liverpool,Wolves,3,1,H,1,1,...,3.28,-2.50,2.02,1.77,2.06,1.83,2.19,1.99,2.07,1.80
378,E0,22/05/2022,16:00,Man City,Aston Villa,3,2,H,0,1,...,3.36,-2.25,2.06,1.84,2.05,1.86,2.09,2.03,2.01,1.87
379,E0,22/05/2022,16:00,Norwich,Tottenham,0,5,A,0,2,...,2.40,1.50,1.95,1.95,1.96,1.94,2.16,1.98,1.99,1.89

# Read .csv from Multiple URLs with Pandas

##### https://www.football-data.co.uk/mmz4281/2122/E0.csv

#### Link: root + season + league

In [1]:
##### link structure
"https://www.football-data.co.uk/mmz4281/" + "2122" + "/" + "E0" + ".csv"

'https://www.football-data.co.uk/mmz4281/2122/E0.csv'

In [2]:
# create a root variable
root="https://www.football-data.co.uk/mmz4281/"

In [4]:
import pandas as pd

# Multiple leagues

##### https://www.football-data.co.uk/mmz4281/2122/EO.csv
##### https://www.football-data.co.uk/mmz4281/2122/E1.csv
##### https://www.football-data.co.uk/mmz4281/2122/E2.csv
##### https://www.football-data.co.uk/mmz4281/2122/EC.csv

In [9]:
# Creating a list of leagues
leagues = ['E0', 'E2', 'E3']

#frames is a list used to store multiple DataFrames.
frames = [] 

# looping through leagues, read multiple csv and append it into a list
for league in leagues:
    df = pd.read_csv(root + "2122" + "/" + league + ".csv")
    frames.append(df)

In [6]:
len(frames)

3

In [7]:
frames[2].head(3)

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E3,07/08/2021,15:00,Carlisle,Colchester,0,0,D,0,0,...,1.57,-0.25,1.75,2.05,1.78,2.13,1.82,2.13,1.75,2.08
1,E3,07/08/2021,15:00,Exeter,Bradford,0,0,D,0,0,...,1.65,0.00,1.80,2.05,1.79,2.12,1.87,2.12,1.80,2.03
2,E3,07/08/2021,15:00,Forest Green,Sutton,2,1,H,1,0,...,1.60,-0.25,1.98,1.83,1.93,1.95,2.03,1.99,1.91,1.90

# Multiple Seasons

In [7]:
leagues = ['E0', 'E2', 'E3']

Frames = []

# loop through range of seasons and insert new column
for league in leagues:
    for season in range(15,21): #range of seasons
        df=pd.read_csv(root + str(season) + str(season+1) + "/" + league + ".csv")
#       df['season'] = season
       df.insert(1, 'season', season)
       frames.append(df)

IndentationError: unindent does not match any outer indentation level (<string>, line 10)

In [ ]:
leagues = ['E0', 'E2', 'E3']

frames = []

# loop through range of seasons and insert new column
for league in leagues:
    for season in range(15, 21):   # range of seasons
        
        df = pd.read_csv(
            root + str(season) + str(season + 1) + "/" + league + ".csv"
        )

        # insert new column
        df.insert(1, 'season', season)

        # append dataframe into list
        frames.append(df)

In [8]:
len(frames)

NameError: name 'frames' is not defined

In [9]:
frames(17)

NameError: name 'frames' is not defined

# Organize All The Data in a Dictionary

In [10]:
# create a dictionary with original name of league as key
dict_countries = {
    'Spanish La Liga':'SP1', 'Spanish Segunda Division':'SP2',
    'German Bundesliga':'D1',
    'English Premier league':'E0', 'English League 1':'E2','English League 2':'E3'
    }

In [12]:
# get a dictionary element
dict_countries['German Bundesliga']

'D1'

In [13]:
dict_historical_data = {}

# looping through key elements
for league in dict_countries:
    frames = [] # one dataframe per league
    for season in range(15,21):
        df = pd.read_csv(root + str(season) + str(season+1) + "/" + dict_countries[league]+ ".csv")
        df.insert(1 , 'season', season)
        frames(

NameError: name 'root' is not defined